#!/bin/bash
# Fired by rpt.conf [events] when RPT_TXKEYED goes 0 -> 1 (transmitter keyed)
NODE_NUMBER="__NODE_NUMBER__"
/usr/sbin/asterisk -rx "manager userevent ASL3Event|EventName: txkeyed_true|Node: ${NODE_NUMBER}" > /dev/null 2>&1
